apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: ducta11-kubernetes-simple-express-reverseproxy
  name: ducta11-kubernetes-simple-express-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
        service: ducta11-kubernetes-simple-express-reverseproxy
  template:
    metadata:
      labels:
        service: ducta11-kubernetes-simple-express-reverseproxy
    spec:
      containers:
      - image: khongthequenbluestar/simple-reverse-proxy
        name: ducta11-kubernetes-simple-express-reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always