apiVersion: v1
kind: Service
metadata:
  labels:
    service: ducta11-kubernetes-simple-express-reverseproxy
  name: ducta11-kubernetes-simple-express-reverseproxy-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: ducta11-kubernetes-simple-express-reverseproxy